export const initialAccounts = [
    { username: "openai", profile_pic: "" },
    { username: "googledeepmind", profile_pic: "" },
    { username: "nvidia", profile_pic: "" },
    { username: "metavision", profile_pic: "" },
    { username: "sama", profile_pic: "" },
    { username: "yacine", profile_pic: "" },
    { username: "karpathy", profile_pic: "" },
    { username: "lexfridman", profile_pic: "" },
    { username: "mkbhd", profile_pic: "" },
    { username: "verge", profile_pic: "" },
    { username: "wired", profile_pic: "" },
    { username: "techcrunch", profile_pic: "" },
    { username: "arstechnica", profile_pic: "" },
    { username: "engadget", profile_pic: "" },
    { username: "linustech", profile_pic: "" },
    { username: "mrwhosetheboss", profile_pic: "" },
    { username: "austinnotduncan", profile_pic: "" },
    { username: "ijustine", profile_pic: "" },
    { username: "zuck", profile_pic: "" },
    { username: "mosseri", profile_pic: "" },
    { username: "satyanadella", profile_pic: "" },
    { username: "sundarpichai", profile_pic: "" },
    { username: "tim_cook", profile_pic: "" },
    { username: "elonmusk", profile_pic: "" }, // Note: Elon is on X mostly, but maybe Threads exists? Unlikely active. 
    // Let's stick to active threads users or companies
    { username: "netflix", profile_pic: "" },
    { username: "spotify", profile_pic: "" },
    { username: "awscloud", profile_pic: "" },
    { username: "google", profile_pic: "" },
    { username: "microsoft", profile_pic: "" },
    { username: "apple", profile_pic: "" },
    { username: "android", profile_pic: "" },
    { username: "reactjs", profile_pic: "" },
    { username: "vercel", profile_pic: "" },
    { username: "supabase", profile_pic: "" },
    // Add more accounts here to reach 50
];
